version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  redis_data: {}
  redis_backup: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups

  redis:
    image: redis:4.0
    volumes:
      - redis_data:/var/lib/redis
      - redis_backup:/backups

  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
      args:
        requirements_file: production.txt
    image: inxyz/infinity-django:latest
    depends_on:
      - postgres
      - redis
    command: uwsgi.sh
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_READ_DOT_ENV_FILE: 1
      DJANGO_DOT_ENV_FILE: .env_production
      DATABASE_URL: postgres://postgres@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      DJANGO_ADMIN_URL: ^admin/
    env_file:
      - .env_production
    volumes:
      - /var/www/static:/app/staticfiles

  nginx:
    image: nginx:1.12.1
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./compose/nginx/conf.d:/etc/nginx/conf.d:ro
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/:/etc/ssl/certs:ro
      - /var/www/static:/var/www/static
